### PR TITLE
set proper timeout for mocha for this test to work

### PR DESCRIPTION
**Pull request by rubensayshi**

### CODE REVIEW

**Comment by dcousens** [comment]
I think this is acceptable because this test is the only that one that is time based.

The rest can rely on user set timeouts using `mocha --timeout` and such.
I'm going to merge, but I'll ping @jprichardson for comment anyway.

**Comment by dcousens** [comment]
Wait, no, this can also be handled by `mocha --timeout`.  @rubensayshi why is this necessary?

**Comment by dcousens** [comment]
Might revert depending on comments.

**Comment by rubensayshi** [comment]
the `mocha --timeout` (defaults to 2s) is the timeout per test case, for all tests except this one you want that to stay 2s.  
except for this one, it should have 15s to match the 3 intervals you're using.  

using `this.timeout` inside a `describe` or `it` sets the timeout just for that 1 test case.

**Comment by jprichardson** [comment]
I'm against this, `mocha --timeout` should be used to control timeouts since the timing of these functions is due to environmental conditions. -1 for me.

**Comment by rubensayshi** [comment]
`mocha --timeout` is a global timeout, if you would set that to 15s then that would mean all test cases have a 15s timeout allowed.

this test is written to allow 3 attempts with 3s intervals, prior to me touching it, which it can't really do because the mocha default 2s timeout.

**Pull request merged**
